org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.nodaemon=true


minecraft_version=1.12.2
minecraft_version_range=[1.12,1.12.2]
forge_version=14.23.5.2847
forge_version_range=[49,)
loader_version_range=[49,)

mapping_channel=stable
mapping_version=39-1.12

mod_id=semaphore-elementa
mod_name=Semaphore-elementa
mod_license=All-Rights-Reserved
mod_version=1.3.1-SNAPSHOT

mod_group_id=io.github.singlerr.semaphore
mod_authors=singlerr
mod_description=A simple voice chat addon for bi-communication

voicechat_version=2.5.12
voicechat_api_version=2.5.0
elementa_version=665
uc_version=363
mod_menu_version=0.1.0+mc1.12.2

loom.platform=forge

semaphore_base_version=1.0.43
semaphore_version=1.3.9-SNAPSHOT